assets/plugins/updater/plugin.updater.php

Some servers have fopen disabled. If so try cURL instead to get zip file.
There may be a more elegant coding way, but this seems to work?

[F] Allow Updater to try cURL if needed

---

manager/processors/save_content.processor.php

Чтобы можно было перенести ресурс внутрь "соседа", нужно проверять не oldparent, а id существующего ресурса. Иначе эта проверка не даст перенести ресурс внутрь соседа, так как oldparent окажется среди массива parents, что сейчас собственно и происходит в текущей версии.

Смена родителя ресурса на предка соседа

---

assets/lib/MODxAPI/modManagers.php

Surely just a typo: the web_user_settings was used at one place in modManagers.

FIX typo in SQL n modManagers-API

---

assets/plugins/updater/plugin.updater.php
install/assets/plugins/updater.tpl

This is important for custom forks with custom installers because they may get broken if someone clicks the default update button in the home page of the manager.

NEW configurable GitHub repo in updater plugin

---

manager/media/style/default/css/mainmenu.css

On a smartphone etc the 'dimmed' main area when dropdown menus are selected can still be dragged so the dimmed background would no longer cover the main area.

[F] Main menu background cover for touch device

---

manager/includes/document.parser.class.inc.php

Метод присваивает результат переменной $this->documentContent и возвращает этот результат,
а в prepareResponse() присваивает его опять.
К тому же в плагине с событием "OnLoadWebPageCache" мы не сможем изменить documentContent.

getDocumentObjectFromCache()

---

assets/plugins/managermanager/mm.inc.php
assets/plugins/managermanager/readme.html
install/assets/plugins/mgrmgr.tpl

Update version number following a couple of recent fixes.

[F] Update ManagerManager version number to 0.6.3

---

install/actions/action_connection.php
install/connection.collation.php
install/connection.servertest.php
install/functions.php
install/lang/bulgarian.inc.php
install/lang/czech.inc.php
install/lang/danish.inc.php
install/lang/english.inc.php
install/lang/finnish-utf8.inc.php
install/lang/francais-utf8.inc.php
install/lang/german.inc.php
install/lang/hebrew.inc.php
install/lang/italian.inc.php
install/lang/japanese-utf8.inc.php
install/lang/nederlands-utf8.inc.php
install/lang/norwegian.inc.php
install/lang/persian.inc.php
install/lang/polish-utf8.inc.php
install/lang/portuguese-br-utf8.inc.php
install/lang/portuguese.inc.php
install/lang/russian-UTF8.inc.php
install/lang/spanish-utf8.inc.php
install/lang/svenska.inc.php

On PHP 7.2 install crashed with an error:
`Fatal error: Uncaught Error: Call to undefined function getLangs() in /var/www/.../install/actions/action_connection.php:63 Stack trace: #0 /var/www/.../install/index.php(63): include_once() #1 {main} thrown in /var/www/.../install/actions/action_connection.php on line 63`
I moved function getLangs() in /install/functions.php before calling her.

Fix install error on PHP 7.2

---

manager/media/style/default/css/custom.css

For those still using TinyMCE3 this will wrap the toolbar to prevent overflow in container and so it behaves like TinyMCE4.

[I] Wrap TinyMCE3 Toolbar

---

manager/media/style/default/css/tree.css

Межбуквенно расстояние на светлом фоне плохо смотрится, лучше оставить как было до того. А в чёрной прибавлять

кёрнинг для светлой темы

---

manager/media/style/default/css/fonts.css

Suggest adding the icon back in. On older modx/evo versions it had the icon and also appended the element type to the title. Without either it takes a second look to confirm the element type you are editing.

[I] Show element icon

---

manager/media/style/default/css/color.switcher.css

So does not overlay action buttons on mobile

[I] Move color switcher icon

---

manager/actions/welcome.static.php

As idle users can be listed the date is needed as well as the time for last hit in the dashboard 'Online Managers and Members' table

[I] Add date to active users hit time

---

manager/includes/document.parser.class.inc.php

Whit nested events the reference can be lost.

[F] Event reference fix

---

manager/actions/mutate_tv_rank.dynamic.php

Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `evo`.`ihlo_site_tmplvars` ORDER BY rank ASC, id ASC' at line 1

SQL syntax for mysql 8

---

core/src/Controllers/Frame.php
manager/actions/mutate_user.dynamic.php
manager/actions/mutate_web_user.dynamic.php
manager/actions/user_management.static.php
manager/actions/web_user_management.static.php
manager/media/style/default/style.php
manager/views/page/access_permissions.blade.php
manager/views/page/web_access_permissions.blade.php

В меню и в разделах иконки пользователей были без визуальной логики, и повторялись.
Теперь логика появилась: "иконки пользователей в кружке" - меню и разделы для пользователей. Простые "иконки пользователей" - меню и разделы для веб-пользователей.
Пример для пользователей (для веб-пользователей по аналогии):

Связал стили иконок для обычных и web-пользователей в меню и в разделах

---

manager/media/style/default/css/custom.css

Добавил стили для WebKit скролла во всех темах.
В темной стили скролла были, но при переключении темы на другую в Windows странно смотрелся системный скролл (для Mac OS это не так заметно), теперь норм.

2.0 Добавил стили для WebKit скролла

---

manager/actions/category_mgr/skin/sort.tpl.phtml

Там стояла иконка TV, что смущает.
Было:
Стало:

2.0 Заменил иконку на правильную в разделе "Сортировать категории"

---

manager/actions/access_permissions.dynamic.php
manager/actions/mutate_user.dynamic.php
manager/actions/mutate_web_user.dynamic.php
manager/actions/user_management.static.php
manager/actions/web_access_permissions.dynamic.php
manager/actions/web_user_management.static.php
manager/frames/mainmenu.php
manager/media/style/default/style.php

В меню и в разделах иконки пользователей были без визуальной логики, и повторялись.
Теперь логика появилась: "иконки пользователей в кружке" - меню и разделы для менеджеров. Простые "иконки пользователей" - меню и разделы для веб-пользователей.
Пример для менеджеров (для веб-пользователей по аналогии):

1.4.9 Связал стили иконок для обычных и web-пользователей в меню и в разделах

---

manager/actions/category_mgr/skin/sort.tpl.phtml

Там стояла иконка TV, что смущает.
Было:
Стало:

1.4.9 Заменил иконку на правильную в разделе "Сортировать категории"

---

manager/actions/eventlog.dynamic.php
manager/media/style/default/css/custom.css

Когда в "Просмотре событий" становится много станиц, то благодаря классу nowrap таблица растягивается до невероятных размеров в ширину. Добавил стили чтобы номера страниц и код события переносились.

eventlog wrap link

---

assets/snippets/phpthumb/snippet.phpthumb.php

To prevent thumbnail images to be detected as banners by adblockers.
issue https://github.com/evolution-cms/evolution/issues/1196

Replace suffix contains substing "ad"

---

assets/plugins/tinymce4/gsettings/gsettings.body.inc.html
assets/plugins/tinymce4/gsettings/gsettings.row.inc.html
assets/plugins/tinymce4/gsettings/gsettings.rows.inc.php
manager/media/style/default/css/custom.css

Исправил вывод настроек для tinyMCE в разделе "Конфигурация":
- Сделал их удобнее (вывел название [(ключа)], починил label);
- Привел оформление к одному стилю (поправил код, верстку и классы).
До:
После:

Исправил вывод настроек tinyMCE

---

manager/media/style/default/css/custom.css
manager/views/page/system_settings/file_browser.blade.php
manager/views/page/system_settings/general.blade.php

Поправил вывод списков в разделе "Конфигурация", списки теперь шириной в 50% вместо auto.
По-моему, с единым размером выглядит чутка приятнее.
До:
После:
Эти правки ни на что не влияют и я пойму, если они будут отклонены :)

Поправил вывод списков в разделе "Конфигурация"

---

core/src/Core.php

getChildIds  function din't work properly for multiple ids because of mistake in sprintf.
`sprintf("%d", "2,3,4")`
returns "2".

fix mistake in getChildIds core function

---

manager/media/browser/mcpuk/themes/evo/style.css

Folder icon unicode was changed https://fontawesome.com/icons/folder?style=solid
The older one (f114) exists only in FA4

Fix "New Folder" icon

---

manager/includes/tmplvars.inc.php

When editing field with type URL, when data is loaded from DB, a double "- " was cut from the url.
In addition, the schema prefix was searched for throughout the url, not at the begin.
Therefore, the url containing for example 'http://' in the middle was also loaded with an error.
For example, instead of 
«http://url.com/?link--redirect=http://url2.com/»
received
«http://» + «url.com/?linkredirect=url2.com/»

Double "-" will be lost when editing a url.

---

manager/actions/eventlog.dynamic.php

With many events in logs list pagination become unusable.
Remove "nowrap" class from the table fix this.
modified:   manager/actions/eventlog.dynamic.php

Change table format for logs list so pagination become usable.

---

manager/media/style/default/css/mainmenu.css

In dropdowns (list of modules) icons with class .fas or .fab are shown without margins.
This will fix it.
modified:   manager/media/style/default/css/mainmenu.css

Fix css for the fontawesome icons in manager

---

manager/media/style/default/style.php

modified:   manager/media/style/default/style.php
Fix icon class for locked items (templates, snippets, etc) in manager.

Change string to a correct for a fontawesome class in manager.

---

core/functions/actions/mutate_content.php

PHP Warning: trim() expects parameter 1 to be string, array given in Plugin OnDocFormTemplateRender[templatesEdit 3]:73

expects parameter 1 to be string, array given

---

core/src/Core.php
core/src/ExceptionHandler.php

simple example:
```php
Route::get('/helloworld', function() {
$undefined = app()->undefined;
});
```
this route should not show 404 page

Execute parser for show 404 page only on notFound and notAllowed exceptions

---

core/src/Parser.php

Проблема:
не удается задать путь к blade-шаблонам для доклистера.
Причина: 
В методе `setTemplatePath` проверяется свойство `$this->bladeEnabled`, и путь будет задан только в том случае если оно равно `true`. Но вот значение этого свойства меняется только в методе `parseChunk`, в зависимости от того, какой обрабатывается шаблон. Т.е. если вывести не-blade-шаблон, то сразу после этого задать путь не удастся.
Поэтому считаю будет правильнее проверять не свойство `$bladeEnabled`, а свойство `$blade`.

fix views path setting

---

core/config/app.php
core/custom/config/middleware.php.sample
core/src/Core.php
core/src/Providers/RoutingServiceProvider.php

Added support for middleware custom priority order, aliases for assigning to routes.
Fixed models to routes binding.
```php
Route::get('/documents/{document}', function(SiteContent $document) {
return $document->pagetitle;
});
```

middleware priority, aliases, fixed bindings

---

manager/includes/document.parser.class.inc.php

$this->contentTypes всегда равен NULL. Кто ввёл эту переменную и зачем разбираться некогда.
Проверку выполняем по нормальному.

Поддержка contentType
