evolution-cms/evolution

- manager/includes/extenders/ex_modifiers.inc.php
Error : Undefined property: DocumentParser::$filter
> Error : Undefined property

- install/config.inc.tpl
> Извиняюсь за творчество

- manager/frames/1.php
https://github.com/evolution-cms/evolution/issues/87
> [F] #87 missing OnManagerTopPrerender

- manager/processors/duplicate_content.processor.php
> [F] #99 Use config['docid_incrmnt_method'] when duplicating resources

- manager/includes/document.parser.class.inc.php
Improvement as per #55 using `$modx->atBindFileContent()` to include file-contents for Chunks.
Case-insensitive calls possible:
- `{{@FILE:assets/chunks/header.html}}`
- `{{@file:assets/chunks/header.html}}`
- `{{@File:assets/chunks/header.html}}`
> [I] #55 @FILE for chunks - {{@FILE:assets/chunks/header.html}}

- manager/actions/help/02Documentation.php
Remove version number completely from description.
> [F] Update 02Documentation.php

- manager/actions/help/01About_EVO.php
Help section outdated and not needed as there is a 'documentation' tab with all help and forum links.
> [F] Update 01About_EVO.php

- assets/docs/changelog.txt
> [F] Update changelog.txt

- manager/includes/lang/english.inc.php
Make help sub section titles consistent.
Note sure if it should be 'EVO', 'Evolution' or 'Evolution CMS' but I think more consistency is needed.
> [F] Update english.inc.php

- assets/modules/store/css/style.css
- assets/modules/store/template/main.html
first step updating extras module styles and layout:
- bootstrap grid layout
- views option (list, 3 column blocks, 2 column blocks)
-collapsible sidebar nav
- more info in popup
> updated Extras Module styles and layout

- install/actions/action_install.php
- install/actions/action_summary.php
- install/actions/tpl_mode.html
- install/actions/tpl_options.html
- install/style.css
updated install css to match new default theme
+ minor updated on step progreess bar
> updated install css to match new default theme 

- manager/actions/mutate_templates.dynamic.php
Не верное отображение символов
> Не верное отображение символов

- manager/processors/cache_sync.class.processor.php
speed up cache file creation
reducing server load
> fixed cache build

- assets/plugins/qm/css/style.css
- assets/plugins/qm/qm.inc.php
For screen less than 728px the css needed fixing. Also for left/right toolbar position display the 'close' icon was missing. A few css lines tidied up too.
> [F] Fix QM+ toolbar css

- manager/includes/document.parser.class.inc.php
Возврат рабочей функции из старых версий
public function makePageCacheKey($id){
> work function

- manager/actions/mutate_user.dynamic.php
- manager/actions/mutate_web_user.dynamic.php
Ensure dropdown list of countries is sorted alphabetically
>  [F] Manager and User account country list sort

- manager/includes/document.parser.class.inc.php
https://github.com/evolution-cms/evolution/issues/301
> Remain fix 2

- assets/plugins/updater/plugin.updater.php
- install/assets/plugins/updater.tpl
install did not run if Evo was in a sub-folder
>  [F] Make updater installer run when in subfolder

- manager/actions/welcome.static.php
Make dashboard 'manager user' and 'web user' titles consistent with top menu.
> [F] Dashboard user titles

- assets/plugins/elementsintree/assets/txt_content.tpl
fixed but need unicode versions adding to style/default/style.php.
> [F] Module icon

- manager/actions/logging.static.php
- manager/actions/mutate_content.dynamic.php
- manager/media/style/default/css/custom.css
+ change resource publish/unpublish date icon to delete icon
>  [F] Improve manager log clear date icon formatting

- manager/media/rss/extlib/Snoopy.class.inc
HTTPS RSS feeds were not working for some server configurations. Latest version fixes this.
var $curl_path = false;
// deprecated, snoopy no longer uses curl for https requests,
// but instead requires the openssl extension.
> [F] Update Snoopy for MagpieRSS

- assets/modules/store/core.php
Check for open_basedir and safe_mode not needed for >= php5.6
> [F] Extras curl followlocation fix

- manager/processors/delete_category.processor.php
- manager/processors/delete_content.processor.php
- manager/processors/delete_message.processor.php
PSR2 coding standards
Shall fix for the other files once this is merged
> PSR2 coding standards

- assets/plugins/codemirror/codemirror.plugin.php
- manager/media/style/default/js/modx.js
https://github.com/evolution-cms/evolution/issues/389
>  Quickly create / edit in a template

- manager/includes/document.parser.class.inc.php
https://github.com/evolution-cms/evolution/issues/404
> PHP 7.2: count() Parameter must be an array

- manager/processors/login.processor.php
https://github.com/evolution-cms/evolution/issues/290
https://github.com/evolution-cms/evolution/issues/48
> htmlspecialchars password

- assets/plugins/managermanager/widgets/mm_hidefields/mm_hidefields.php
dropdown was hiding but label was not
> [F] fix hiding which_editor label

- assets/plugins/managermanager/js/jquery.ddMM.js
Which_editor field was not being moved with the resource content in ManagerManager
https://github.com/evolution-cms/evolution/issues/433
> [F] Moving which_editor with resource content for MM

- manager/includes/document.parser.class.inc.php
https://github.com/evolution-cms/evolution/issues/455
> eval() mergeConditionalTagsContent()

- assets/plugins/managermanager/js/jquery.ddMM.js
- assets/plugins/managermanager/widgets/mm_hidefields/mm_hidefields.php
Hide tv separator if a tv separator is above moved content field
Make sure content separator is hidden when hiding content
> [F] MM couple of fixes for moving and hiding

- manager/includes/document.parser.class.inc.php
Fix so works when Evo is installed to subfolder
> [F] Fix Information tab logo path

- assets/plugins/qm/css/navButtons.css
- assets/plugins/qm/css/style.css
Make sure the ID text size is same as buttons and does not use whatever the website style is.
> [F] Quick Manager+ ID text fix

- manager/frames/1.php
Standardise so IDs used on all sections (as on main menu) for easier customisation.
> [I] Add right menu section ids

- assets/plugins/updater/lang/english.php
- assets/plugins/updater/plugin.updater.php
- install/assets/plugins/updater.tpl
Adds functionality for 'commits' type using additional 'Commit branch' parameter.
https://github.com/evolution-cms/evolution/issues/261
> [I] Commits for Updater Plugin

- manager/processors/save_content.processor.php
@dmi3yy requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/evolution-cms/evolution/
> Scrutinizer Auto-Fixes

- manager/frames/mainmenu.php
- manager/includes/lang/english.inc.php
Pending confirmation or otherwise...
https://github.com/evolution-cms/evolution/issues/567
> [I] Change manager 'home' to 'dashboard'

- manager/media/style/default/css/custom.css
ref: https://github.com/evolution-cms/evolution/issues/485
> [F] Prevent long select option text values overflowing container

- manager/actions/search.static.php
Searching from 'Tools' -> 'Search' could return incorrect results when searching using main fields plus another search criteria.
> [F] Fix search using main fields + another criteria

- manager/includes/accesscontrol.inc.php
- manager/media/style/default/login.tpl
Get values from new system settings and set placeholders with images (or show defaults).
> Login page - set images placeholders

- manager/media/style/default/login.tpl
CSS for login form positions. Left, center, right.
> Login form positions

- manager/media/style/default/login.tpl
> Login page

- manager/actions/mutate_settings/tab1_site_settings.inc.php
ref https://github.com/evolution-cms/evolution/issues/625
> [I] Remove 'Top how many' option as not used

- manager/media/style/default/css/tree.css
Add a little 'breathing space' at the bottom of the menu  tree
> [I] Add space to bottom of menu tree

- manager/processors/execute_module.processor.php
ref: https://github.com/evolution-cms/evolution/pull/647
> [F] fix for module iframe scrolling

- manager/includes/document.parser.class.inc.php
> Ctr+Alt+L on PhpStorm

- manager/media/style/default/ajax.php
https://prnt.sc/jlzuuh Fig ajax get tv list on ONLY_FULL_GROUP_BY sql mode
> Fix strict mode bug on get tv list

- manager/includes/lang/english.inc.php
correct path so works for sub directory installs + reference correct tab.
> [F] Correct message urls

- manager/includes/lang/english.inc.php
Realised I had a custom settings plugin installed that added extra tabs!
Change to path stands.
> [F] revert tab change

- manager/media/style/default/css/mainmenu.css
This css is not needed as far as I can tell + it conflicts with the color switcher.
> [I] Remove css / colour switch conflict

- manager/media/style/default/css/mainmenu.css
make sure top menu logo background is not 'active color'
> [I] Minor logo background fix

- manager/media/style/default/snippets/welcome/RecentInfo.php
> [I] Add time to dashboard resource edit dates

- manager/frames/1.php
- manager/includes/lang/english.inc.php
- manager/media/style/default/css/mainmenu.css
- manager/media/style/default/style.php
Reverts evolution-cms/evolution#735
> Revert " Add site offline warning icon to top menu"

- manager/includes/actionlist.inc.php
Plus a couple of MODX to EVO ... if they are even used.
> [I] Action name for dashboard

- manager/actions/welcome.static.php
stop username wrap if has spaces
Add time to dashboard resource edit dates
> [I] alter recent info table

- manager/processors/save_web_user.processor.php
Roll back api as those commits are still only in dev. Keep fix for saving web user permissions.
ref: https://github.com/evolution-cms/evolution/issues/762
> [F] Fix saving web users

- assets/plugins/extrascheck/lang/english.php
- assets/plugins/extrascheck/lang/italian.php
- assets/plugins/extrascheck/lang/russian-UTF8.php
- assets/plugins/extrascheck/lang/spanish.php
- install/assets/plugins/OutdatedExtrasCheck.tpl
CHANGED:
Show widget for - AdminOnly is now the default setting
ADDED:
check outdated modx rss news feed
> Updated extrascheck plugin v1.4.5

- manager/frames/tree.php
- manager/includes/lang/english.inc.php
> [I] Add title for theme mode icon

- manager/processors/duplicate_tmplvars.processor.php
- manager/processors/save_plugin.processor.php
Fix mysql 8.0 bug with copy tv and bug with create new plugin without events #809
> Fix mysql 8.0 bug with copy tv #809

- assets/lib/class.modxRTEbridge.php
$modx->getLoginUserType() returned empty string
> Change checking of manager mode

- install/lang/polish-utf8.inc.php
- manager/includes/lang/polish-utf8.inc.php
> Polish translations

- manager/views/page/system_settings.blade.php
- manager/views/page/system_settings/mail_templates.blade.php
вернул текст на табе "Пользователи" на вкладке системных конфигураций, по аналогии с прошлыми версиями таб "пользователи" поставил 3 по очередности
> Мелкая правка в "Системных конфигурациях"

- manager/processors/cache_sync.class.processor.php
Обнаружение уровня ошибки РНР: Обнаружить все
evo 1.4.8
php 7.2.10
mysql 5.6.41
> Undefined index: enable_filter

- core/functions/processors.php
- core/src/Models/SiteContent.php
- manager/processors/delete_content.processor.php
- manager/processors/duplicate_tmplvars.processor.php
- manager/processors/undelete_content.processor.php
fix(core): Error with copy tv with category #993
>  fix(core): Incorrect delete and undelete resource.  

- assets/lib/MODxAPI/MODx.php
php 7.2.10
бд: 5.6.43
evo: 1.4.8
Обнаружение уровня ошибки РНР: Обнаружить все
> Error : Undefined index

- assets/snippets/phpthumb/snippet.phpthumb.php
For use webp converter need add param **webp** for snippet param. And install package _composer require rosell-dk/webp-convert_
> fix(snippet): add webp converter and param webp

- assets/snippets/phpthumb/snippet.phpthumb.php
fix(snippet): update webp validator
>  fix(snippet): update webp validator

- manager/actions/mutate_user.dynamic.php
- manager/actions/mutate_web_user.dynamic.php
- manager/actions/web_user_management.static.php
>  Fix - display thislogin date for users / managers

- manager/actions/mutate_user.dynamic.php
- manager/actions/mutate_web_user.dynamic.php
- manager/actions/web_user_management.static.php
> Fix - display thislogin date for users / managers

- install/cli-install.php
- install/src/controllers/connection.php
- install/src/controllers/connection/collation.php
- install/src/controllers/connection/databasetest.php
- install/src/controllers/connection/servertest.php
- install/src/controllers/install.php
- install/src/controllers/options.php
- install/src/controllers/summary.php
- install/src/functions.php
- install/src/processor/result.php
- install/src/sqlParser.class.php
table_prefix() and sql_escape() are temporary functions.
> installer code cleanup

- install/setup.sql
- manager/includes/document.parser.class.inc.php
Invoked after save data to event_log.
> add(core) add new event OnErrorAlert.

- manager/includes/document.parser.class.inc.php
Reverts evolution-cms/evolution#1100 - we should not accept code that solves somebody's particular problem, at least without detailed description of that problem.
> Revert "updatePubStatusChecked"

- manager/actions/logging.static.php
> Changed the icon to the correct one

- manager/media/style/default/snippets/welcome/RecentInfo.php
Поправил виджет "Недавно созданные/отредактированные ресурсы" для соответствия с версией 1.4.9
> 2.0 Поправил виджет как в 1.4.9

- manager/actions/logging.static.php
> 1.4.9. Поправил иконку на правильную

- manager/media/style/default/css/custom.css
В стилях была ошибка, из-за чего скролл появлялся только при наведении.
Убрал стили, скрывающий уголок-ресайзер.
> 2.0.x Исправил стили для кастомного скролла

- manager/media/style/default/css/custom.css
В стилях была ошибка, из-за чего скролл появлялся только при наведении.
Убрал стили, скрывающий уголок-ресайзер.
> 1.4.x Исправил стили для кастомного скролла

- core/src/Console/Packages/InstallPackageRequireCommand.php
- core/src/Console/Packages/PackageCreateCommand.php
refactor (console) add param packageName to create:package
> refactor (console) add param packageName to create:package

- assets/modules/store/installer/instprocessor-fast.php
- assets/modules/store/installer/instprocessor.php
- install/cli-install.php
- install/instprocessor.php
- manager/actions/mutate_plugin_priority.dynamic.php
This PR adds plugins priority incremental saving on first cms install and in store module.
Also priority settings page fixed.
> [F] Plugins priority

- manager/media/script/tabpane.js
When the last active tab is saved to cookie, and you switching from one document to another with fewer tabs, there is no active tab.
This PR fixing it.
Also method for removing tabs added.
> [F] Fix for empty active tab, 1.4.x

- assets/snippets/DocLister/snippet.DLSitemap.php
Object of class Closure could not be converted to string
> Prepare fixed

- manager/media/style/default/css/custom.css
ref: https://github.com/evolution-cms/evolution/issues/1232
> Fix fullscreen tinymce hiding buttons

- manager/media/style/default/css/main.css
> Fix right arrow icon before element description

- manager/media/style/default/css/mainmenu.css
> Fixed left menu styles

- core/src/Traits/Settings.php
> Fix enable_cache

- manager/actions/bkmanager.static.php
> update bk manager

- assets/modules/store/installer/instprocessor-fast.php
- assets/modules/store/installer/instprocessor.php
- install/src/controllers/install.php
- install/src/template/actions/install.php
> [F] [2.0.x] Keep priority of plugins events during cms update

- manager/media/browser/mcpuk/themes/evo/style.css
Again, some FA5 free icons exists only in solid style with font-weight:900
> fixing icons

- manager/processors/save_user.processor.php
При попытке создания юзера не админом получаем ошибку.
У модели ManagerUser нет поля role, оно в модели UserAttribute. 
Ошиблись названием модели http://joxi.ru/n2YqNMnuZ95gp2
> При попытке создания юзера не админом получаем ошибку.

- assets/modules/store/template/main.html
> Added classes to restyle the Extras

- manager/media/browser/mcpuk/core/browser.php
> Error : Undefined index: dirs

- core/functions/processors.php
- core/src/Core.php
- core/src/ManagerTheme.php
- core/src/Models/UserSetting.php
- core/src/Models/WebUser.php
- install/stubs/migrations/2020_10_05_154230_drop_manager_user_tables.php
- install/stubs/migrations/2020_10_05_184820_update_web_user_attributes_table.php
- manager/actions/mutate_web_user.dynamic.php
- manager/processors/login.processor.php
- manager/processors/save_web_user.processor.php
core (refactor) refactor user settings and add migration for delete table
> core (refactor) refactor user settings and add migration

- manager/processors/login.processor.php
Fixed undefined $_SESSION['mgrPermissions']['name']
> Fixed undefined

- core/src/TemplateProcessor.php
usage example:
```php
<?php
namespace EvolutionCMS\App\Controllers;
use EvolutionCMS\App\Services\Activity;
class ActivityController
{
public function __construct(Activity $activity)
{
evo()->addDataToView([
'activity' => $activity->getList([
'display' => 10,
'filters' => 'tv:date:>=:' . time(),
]),
]);
}
}
```
> dependency injections in template controllers

- manager/media/style/default/css/mainmenu.css
Fix come classes in mainmenu.css for icons from the fontawesome.
> Fix classes for the fontawesome icons

- assets/snippets/phpthumb/phpthumb.bmp.php
- assets/snippets/phpthumb/phpthumb.class.php
- assets/snippets/phpthumb/phpthumb.functions.php
- assets/snippets/phpthumb/phpthumb.gif.php
PHP 7.4 curly brace substring compatibility
https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.15
> update phpthumb to 1.7.15-202004301145

- assets/modules/store/installer/instprocessor.php
Replace $modx->db to EvolutionCms()->getDatabase()
Fix $table_prefix variables(use new db params dabase and prefix)
> Fix $db params in extras module(table_prefix)

- core/src/Database.php
- manager/actions/mutate_web_user.dynamic.php
Fix Database.php settings name for connection ($modx->db->connect();)
Fix bug for tvs, which using in user form
> Fix $modx->db->connect() and tv render in mutate_web_user.dynamic

- README.md
> Added the new English Forum to the References links

- core/src/Core.php
> users refactor

- core/src/Core.php
core (fix) add check for admin in getDocumentObjectFromCacheFunction
> core (fix) add check for admin

- core/src/Traits/Path.php
previously defined here - https://github.com/evolution-cms/evolution/blob/3.x/core/src/AbstractLaravel.php#L211
> removed environment method

- core/lang/en/pagination.php
- core/src/Providers/PaginationServiceProvider.php
Now can just call `{{ $items->links() }}` to use default links view.
> Pagination default lang, default views fix

- core/lang/nl/global.php
Add-ons is a more logical name for the Extra's
> Change Extra's to Add-ons

- core/composer.json
- core/src/Console/Scheduling/ScheduleListCommand.php
- core/src/Console/Scheduling/ScheduleRunCommand.php
- core/src/Providers/ArtisanServiceProvider.php
- core/vendor/dragonmantank/cron-expression/CHANGELOG.md
- core/vendor/dragonmantank/cron-expression/LICENSE
- core/vendor/dragonmantank/cron-expression/README.md
- core/vendor/dragonmantank/cron-expression/composer.json
- core/vendor/dragonmantank/cron-expression/phpstan.neon
- core/vendor/dragonmantank/cron-expression/src/Cron/AbstractField.php
- core/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php
- core/vendor/dragonmantank/cron-expression/src/Cron/DayOfMonthField.php
- core/vendor/dragonmantank/cron-expression/src/Cron/DayOfWeekField.php
- core/vendor/dragonmantank/cron-expression/src/Cron/FieldFactory.php
- core/vendor/dragonmantank/cron-expression/src/Cron/FieldFactoryInterface.php
- core/vendor/dragonmantank/cron-expression/src/Cron/FieldInterface.php
- core/vendor/dragonmantank/cron-expression/src/Cron/HoursField.php
- core/vendor/dragonmantank/cron-expression/src/Cron/MinutesField.php
- core/vendor/dragonmantank/cron-expression/src/Cron/MonthField.php
Створення консольної команди описано https://github.com/evolution-cms/example-package#console. Щоб додати розклад, потрібно в файл команди додати метод `schedule()`.
```
/**
* Define the command's schedule.
*
* @param  \Illuminate\Console\Scheduling\Schedule  $schedule
* @return void
*/
public function schedule(Schedule $schedule)
{
$schedule->command(static::class)->everyFiveMinutes();
}
```
В методі `boot()` сервіс провайдера ініціалізувати розклад.
```
if (count($this->commands)) {
$this->app->booted(function () {
$this->defineConsoleSchedule();
});
}
```
Додати необхідні методи в файл сервіс провайдера
```
/**
* Define the application's command schedule.
*
* @note check timezones list timezone_identifiers_list()
*
* @return void
*/
protected function defineConsoleSchedule()
{ …
```
> [ADD] Schedule.

- assets/modules/docmanager/tv.ajax.php
- assets/plugins/qm/qm.inc.php
- manager/includes/document.parser.class.inc.php
- manager/includes/extenders/dbapi.mysqli.class.inc.php
- manager/includes/lang/japanese-utf8.inc.php
- manager/includes/tmplvars.inc.php
- manager/media/browser/mcpuk/config.php
refactor and code cleanup.
https://github.com/evolution-cms/evolution/pull/2114/commits/ee368c4a3824f542437008cfd7880d4eae905743
new feature `REDIRECT_JS`
https://github.com/evolution-cms/evolution/pull/2114/commits/0ef385b3158c44a88ff1c4b3e29073c65134125a
fix add replace table prefix 
I'm planning on improving v3 next month.
> 1.4.x refactor
